import test from 'node:test';import assert from 'node:assert/strict';import { proxy } from '../server/proxy';
const key='sk-test-secret-credential-123456789';const body={provider:'openai',model:'gpt-6-luna',prompt:'说明',input:'フレーム',maxTokens:128,reasoning:'none'};
const req=(data:unknown=body,auth=`Bearer ${key}`,origin='https://example.com')=>new Request('https://example.com/api/generate',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Authorization:auth},body:JSON.stringify(data)});
const mock=(data:unknown,status=200)=>(async()=>new Response(JSON.stringify(data),{status})) as typeof fetch;
test('fixed official target, no persistence, no owner fallback, no cache',async()=>{let target='',sent:any;const r=await proxy(req(),'generate',(async(url,init)=>{target=String(url);sent=init;return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'日本語'}]}],usage:{input_tokens:3,output_tokens:5}}));}) as typeof fetch);assert.equal(target,'https://api.openai.com/v1/responses');assert.equal(JSON.parse(sent.body).store,false);assert.equal(sent.headers.Authorization,`Bearer ${key}`);assert.equal(sent.redirect,'error');assert.match(r.headers.get('Cache-Control')!,/no-store/);assert.deepEqual(await r.json(),{text:'日本語',usage:{input:3,output:5}});assert.equal((await proxy(req(body,''),'generate',mock({}))).status,401);});
test('reject foreign origin, arbitrary URL, oversized requests and unreviewed provider',async()=>{let calls=0;const fetcher=(async()=>{calls++;return new Response('{}');}) as typeof fetch;assert.equal((await proxy(req(body,`Bearer ${key}`,'https://evil.com'),'generate',fetcher)).status,403);assert.equal((await proxy(req({...body,url:'https://evil.com'}),'generate',fetcher)).status,400);assert.equal((await proxy(req({...body,input:'x'.repeat(80000)}),'generate',fetcher)).status,400);assert.equal((await proxy(req({...body,provider:'aihubmix'}),'generate',fetcher)).status,400);assert.equal(calls,0);});
test('sanitized structured errors never echo provider message or credential',async()=>{for(const [status,code,expected] of [[401,'invalid_key','invalid_key'],[429,'rate_limit_exceeded','rate_limit'],[429,'insufficient_quota','insufficient_quota'],[404,'model_not_found','model_access'],[500,'server_error','provider_error']] as const){const r=await proxy(req(),'generate',mock({error:{code,message:'raw provider secret '+key}},status));const data=await r.text();assert.ok(!data.includes(key));assert.ok(!data.includes('raw provider'));assert.equal(JSON.parse(data).error.code,expected);}});
test('guard output, refusal/incomplete, redact accidentally echoed key',async()=>{const r=await proxy(req(),'generate',mock({output:[{content:[{type:'output_text',text:'echo '+key}]}]}));assert.ok(!(await r.text()).includes(key));assert.equal((await proxy(req(),'generate',mock({status:'incomplete',output:[]}))).status,422);assert.equal((await proxy(req(),'generate',mock({output:[]}))).status,422);assert.equal((await proxy(req(),'generate',mock({output:[{content:[{type:'output_text',text:'x'.repeat(32001)}]}]}))).status,422);});
test('server per-credential concurrency is bounded and released',async()=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);const fetcher=(async()=>{await gate;return new Response(JSON.stringify({output_text:'ok'}));}) as typeof fetch;const pending=[proxy(req(),'generate',fetcher),proxy(req(),'generate',fetcher),proxy(req(),'generate',fetcher)];await new Promise(r=>setTimeout(r,10));assert.equal((await proxy(req(),'generate',fetcher)).status,429);release();await Promise.all(pending);assert.equal((await proxy(req(),'generate',mock({output_text:'ok'}))).status,200);});
test('models endpoint is credential bound and contains no secrets',async()=>{const r=await proxy(req({provider:'openai'}),'models',mock({data:[{id:'gpt-6-luna'},{id:'bad key space'},{id:123}]}));assert.deepEqual(await r.json(),{models:['gpt-6-luna']});});
test('401 explains provider mismatch rather than falsely asserting all keys are invalid',async()=>{const official=await proxy(req(),'generate',mock({error:{code:'invalid_api_key'}},401));const data=await official.json() as {error:{message:string}};assert.match(data.error.message,/OpenAI 官方/);assert.match(data.error.message,/提供商对应/);});

test('DeepSeek and custom chat use appropriate protocol and usage',async()=>{for(const provider of ['deepseek','custom']){let target='',sent:any;const r=await proxy(req({...body,provider,customUrl:provider==='custom'?'https://aihubmix.com/v1/chat/completions':'',model:provider==='deepseek'?'deepseek-flash':'gpt-6-luna'}),'generate',(async(url,init)=>{target=String(url);sent=JSON.parse(String(init?.body));return new Response(JSON.stringify({choices:[{message:{content:'結果'},finish_reason:'stop'}],usage:{prompt_tokens:2,completion_tokens:3}}));}) as typeof fetch);assert.equal(target,provider==='deepseek'?'https://api.deepseek.com/chat/completions':'https://aihubmix.com/v1/chat/completions');assert.deepEqual(sent.messages,[{role:'system',content:'说明'},{role:'user',content:'フレーム'}]);assert.equal(sent.max_tokens,128);assert.equal(sent.stream,false);if(provider==='deepseek')assert.equal(sent.thinking.type,'disabled');assert.deepEqual(await r.json(),{text:'結果',usage:{input:2,output:3}});}});
test('custom URL rejects SSRF, credentials, query params and lookalike domains before forwarding',async()=>{let calls=0;const fetcher=(async()=>{calls++;return new Response('{}');}) as typeof fetch;for(const customUrl of ['http://aihubmix.com/v1','https://127.0.0.1/v1','https://169.254.169.254/v1','https://localhost/v1','https://aihubmix.com.evil.com/v1','https://user:password@aihubmix.com/v1','https://aihubmix.com/v1?key=secret','https://aihubmix.com:8080/v1','https://unknown-api.example/v1']){assert.equal((await proxy(req({...body,provider:'custom',customUrl}),'generate',fetcher)).status,400);}assert.equal(calls,0);});
test('custom base URL normalization and models routing',async()=>{for(const [customUrl,expected] of [['https://aihubmix.com/v1/','https://aihubmix.com/v1/models'],['https://openrouter.ai/api/v1/chat/completions','https://openrouter.ai/api/v1/models'],['https://api.openai.com/v1/responses','https://api.openai.com/v1/models']]){let target='';await proxy(req({provider:'custom',customUrl}),'models',(async(url)=>{target=String(url);return new Response(JSON.stringify({data:[]}));}) as typeof fetch);assert.equal(target,expected);}});
test('local model endpoints are Docker/local-only, bounded to known ports, and allow no key',async()=>{
  let called='',authorization:string|undefined;
  const fetcher=(async(url,init)=>{called=String(url);authorization=new Headers(init?.headers).get('authorization')??undefined;return new Response(JSON.stringify({data:[{id:'qwen3.6-35b-a3b'}]}));}) as typeof fetch;
  const lm={provider:'local',localProvider:'lmstudio',customUrl:'http://127.0.0.1:1234/v1'};
  assert.equal((await proxy(req(lm,''),'models',fetcher)).status,400);
  const listed=await proxy(req(lm,''),'models',fetcher,true);assert.equal(listed.status,200);assert.equal(called,'http://127.0.0.1:1234/v1/models');assert.equal(authorization,undefined);assert.deepEqual(await listed.json(),{models:['qwen3.6-35b-a3b']});
  for(const connection of [{...lm,customUrl:'http://127.0.0.1:22/v1'},{...lm,customUrl:'http://192.168.1.2:1234/v1'},{...lm,customUrl:'http://127.0.0.1:1234/admin'}])assert.equal((await proxy(req(connection,''),'models',fetcher,true)).status,400);
});
test('local model generation omits auth when blank and forwards an optional local token',async()=>{
  const local={provider:'local',localProvider:'lmstudio',customUrl:'http://localhost:1234/v1',model:'qwen3.6-35b-a3b',prompt:'简短解释',input:'フレーム',maxTokens:128,reasoning:'none',stream:false};
  for(const auth of ['',`Bearer ${key}`]){let headers:Headers|undefined;const response=await proxy(req(local,auth),'generate',(async(_url,init)=>{headers=new Headers(init?.headers);return new Response(JSON.stringify({choices:[{message:{content:'日语解释'}}],usage:{prompt_tokens:5,completion_tokens:6}}));}) as typeof fetch,true);assert.equal(response.status,200);assert.equal(headers?.get('authorization'),auth?`Bearer ${key}`:null);assert.deepEqual(await response.json(),{text:'日语解释',usage:{input:5,output:6}});}
});
test('chat truncation and refusal are bounded failures',async()=>{for(const choice of [{message:{content:'partial'},finish_reason:'length'},{message:{content:null,refusal:'no'},finish_reason:'stop'}]){assert.equal((await proxy(req({...body,provider:'deepseek'}),'generate',mock({choices:[choice]}))).status,422);}});
test('network errors remain retryable and diagnostic details never include raw error or keys',async()=>{const result=await proxy(req(),'generate',(async()=>{throw Object.assign(new Error('secret '+key),{cause:{code:'ECONNRESET',message:key}});}) as typeof fetch);const data=await result.json() as any;assert.equal(data.error.code,'network');assert.equal(data.error.retryable,true);assert.match(data.error.message,/连接被中断/);assert.ok(!JSON.stringify(data).includes(key));});
