import test from 'node:test';import assert from 'node:assert/strict';
import { Scheduler } from '../core/scheduler';import { example, emptyCell, type Generate, type RunOptions } from '../core/types';import { descendants, topological } from '../core/graph';import { parseSheet,serialize,csv } from '../core/storage';import { ModelError } from '../model/client';
const opt:RunOptions={mode:'api',concurrency:2,timeout:1000,maxSteps:20,maxRetries:1,totalTimeout:5000,dependencyDelayMs:0,autoRetry:false};
const ok=(text:string)=>({text,usage:{input:10,output:20}});
async function finish(e:Scheduler){const start=Date.now();while(e.busy){if(Date.now()-start>6000)throw new Error('scheduler stuck');await new Promise(r=>setTimeout(r,5));}}
function deferred<T>(){let resolve!:(value:T)=>void;let reject!:(error:Error)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
test('chain uses actual upstream output, deduplicates run, ends at zero',async()=>{const inputs:string[]=[];const e=new Scheduler(example(),async p=>{inputs.push(p.input);await new Promise(r=>setTimeout(r,10));return ok(inputs.length===1?'フレームは枠です。':'老师解读');});e.run(e.targets('all'),opt);e.run(e.targets('all'),opt);await finish(e);assert.deepEqual(inputs,['フレーム','フレームは枠です。']);assert.equal(e.running,0);assert.equal(e.queued,0);assert.equal(e.sheet.rows[0].cells.teacher.status,'done');});
test('edit only invalidates descendants, changed run reuses unaffected results',async()=>{let calls=0;const e=new Scheduler(example(),async p=>{calls++;return ok(p.input+'结果');});await (e.run(e.targets('all'),opt),finish(e));e.edit('row-1','explain','手动改写');assert.equal(e.sheet.rows[0].cells.input.status,'done');assert.equal(e.sheet.rows[0].cells.explain.status,'done');assert.equal(e.sheet.rows[0].cells.teacher.status,'stale');e.run(e.targets('all'),opt);await finish(e);assert.equal(calls,3);});
test('rapid edits abort old request and late result cannot overwrite latest input',async()=>{const old=deferred<ReturnType<typeof ok>>();let calls=0;const e=new Scheduler(example(),async()=>{calls++;return calls===1?old.promise:ok('新结果');});e.run(e.targets('all'),opt);await new Promise(r=>setTimeout(r,5));e.edit('row-1','input','新词1');e.edit('row-1','input','新词2');await finish(e);assert.equal(e.sheet.rows[0].cells.explain.status,'stale');old.resolve(ok('过期结果'));await new Promise(r=>setTimeout(r,5));assert.notEqual(e.sheet.rows[0].cells.explain.value,'过期结果');e.run(e.targets('all'),opt);await finish(e);assert.equal(e.sheet.rows[0].cells.explain.value,'新结果');});
test('cancel active and queued cells, never continues downstream',async()=>{let calls=0;const e=new Scheduler(example(),async()=>{calls++;return new Promise(()=>{});});e.run(e.targets('all'),opt);e.stop();await finish(e);assert.equal(calls,1);assert.equal(e.sheet.rows[0].cells.explain.status,'cancelled');assert.equal(e.sheet.rows[0].cells.teacher.status,'cancelled');});
test('upstream error blocks downstream and explicit retry repairs chain',async()=>{let fail=true,calls=0;const e=new Scheduler(example(),async()=>{calls++;if(fail)throw new ModelError('无效密钥','invalid_key');return ok('成功');});e.run(e.targets('all'),opt);await finish(e);assert.equal(calls,1);assert.match(e.sheet.rows[0].cells.teacher.error!,/上游/);fail=false;e.run(e.targets('all'),opt);await finish(e);assert.equal(calls,3);assert.equal(e.sheet.rows[0].cells.teacher.status,'done');});
test('concurrency never exceeds cap across rows and completes all cells',async()=>{let active=0,peak=0;const e=new Scheduler(example(),async()=>{active++;peak=Math.max(active,peak);await new Promise(r=>setTimeout(r,15));active--;return ok('结果');});for(let i=0;i<5;i++)e.addRow('row-1');e.run(e.targets('all'),opt);await finish(e);assert.equal(peak,2);assert.equal(e.sheet.rows.flatMap(r=>Object.values(r.cells)).filter(c=>c.status==='done').length,18);});
test('hung request hits timeout, count settles to zero',async()=>{const e=new Scheduler(example(),async()=>new Promise(()=>{}));e.run(e.targets('all'),opt);await finish(e);assert.equal(e.sheet.rows[0].cells.explain.status,'error');assert.match(e.sheet.rows[0].cells.explain.error!,/超过/);});
test('cycles rejected and visual sorting does not change graph',()=>{const e=new Scheduler(example(),async()=>ok(''));assert.throws(()=>e.configure({...e.sheet.columns[1],sources:['teacher']}),/循环/);e.moveColumn('teacher',-1);assert.deepEqual(topological(e.sheet.columns),['input','explain','teacher']);assert.deepEqual([...descendants(e.sheet.columns,'input')],['explain','teacher']);});
test('Agent locally validates, corrects only when needed, reports every call',async()=>{let calls=0;const e=new Scheduler(example(),async p=>{calls++;return ok(calls===1?'没有原词':p.input+'释义');});e.run(e.targets('all'),{...opt,mode:'agent',autoRetry:true});await finish(e);assert.equal(calls,3);assert.ok(e.steps.some(s=>s.phase==='修正结果'));assert.ok(e.steps.some(s=>s.phase==='结果检查'&&s.state==='error'));assert.equal(e.sheet.rows[0].cells.explain.usage?.input,20);});
test('Agent step cap, no retry on invalid key, and semantic review counted',async()=>{let calls=0;const e=new Scheduler(example(),async p=>{calls++;return ok(p.prompt.startsWith('检查')?'{"pass":true}':p.input);});e.configure({...e.sheet.columns[1],check:true});e.run(e.targets('all'),{...opt,mode:'agent',maxSteps:2});await finish(e);assert.equal(calls,2);assert.equal(e.sheet.rows[0].cells.explain.status,'done');assert.match(e.sheet.rows[0].cells.teacher.error!,/步数/);const f=new Scheduler(example(),async()=>{throw new ModelError('密钥无效','invalid_key');});f.run(f.targets('all'),{...opt,mode:'agent'});await finish(f);assert.equal(f.steps.length,1);});
test('Agent transient retry is bounded and total deadline stops queue',async()=>{let calls=0;const e=new Scheduler(example(),async()=>{calls++;throw new ModelError('限流','rate_limit',true);});e.run(e.targets('all'),{...opt,mode:'agent',autoRetry:true,apiMaxRetries:1,retryDelayMs:20});await finish(e);assert.equal(calls,2);const f=new Scheduler(example(),async()=>new Promise(()=>{}));f.run(f.targets('all'),{...opt,totalTimeout:30});await finish(f);assert.equal(f.sheet.rows[0].cells.explain.status,'cancelled');assert.equal(f.running,0);});
test('refresh normalizes interrupted states, explicit schema drops credentials and rejects broken data',()=>{const sheet=example();sheet.rows[0].cells.explain.status='running';(sheet as any).apiKey='secret';(sheet.columns[0] as any).token='secret';const output=serialize(sheet);assert.ok(!output.includes('secret'));const restored=parseSheet(JSON.parse(output));assert.equal(restored.rows[0].cells.explain.status,'cancelled');assert.throws(()=>parseSheet({...sheet,columns:[sheet.columns[0],{...sheet.columns[1],sources:['missing']}]}));sheet.rows[0].cells.input.value='=HYPERLINK("evil")';assert.match(csv(sheet),/'=HYPERLINK/);});
test('removing active rows/columns discards late responses without blocking remaining tasks',async()=>{const old=deferred<ReturnType<typeof ok>>();let calls=0;const e=new Scheduler(example(),async()=>{calls++;return calls===1?old.promise:ok('结果');});e.addRow('row-1');e.run(e.targets('all'),{...opt,concurrency:1});await new Promise(r=>setTimeout(r,5));e.removeRow('row-1');await finish(e);old.resolve(ok('旧结果'));assert.equal(e.sheet.rows.length,1);assert.equal(e.sheet.rows[0].cells.teacher.status,'done');assert.equal(e.running,0);});
test('dependent column waits for complete upstream column then 500ms, counts only queued while waiting',async()=>{const events:{phase:string;rowInput:string;at:number}[]=[];const e=new Scheduler(example(),async p=>{const phase=p.prompt.includes('作为日语老师')?'teacher':'explain';events.push({phase,rowInput:p.input,at:Date.now()});await new Promise(r=>setTimeout(r,10));return ok(p.input+'释义');});e.addRow('row-1');e.run(e.targets('all'),{...opt,dependencyDelayMs:500});await new Promise(r=>setTimeout(r,80));assert.equal(e.running,0);assert.equal(e.queued,2);assert.equal(events.length,2);const latest=e.sheet.rows.map(r=>r.cells.explain.completedAt!).reduce((a,b)=>Math.max(a,b),0);await finish(e);const downstream=events.filter(x=>x.phase==='teacher');assert.equal(downstream.length,2);assert.ok(downstream.every(x=>x.at-latest>=495));assert.equal(e.running,0);});
test('stopping in dependency cooldown never sends downstream request',async()=>{let calls=0;const e=new Scheduler(example(),async()=>{calls++;return ok('完成');});e.run(e.targets('all'),{...opt,dependencyDelayMs:500});await new Promise(r=>setTimeout(r,25));assert.equal(e.running,0);assert.equal(e.queued,1);e.stop();await new Promise(r=>setTimeout(r,550));assert.equal(calls,1);assert.equal(e.queued,0);assert.equal(e.sheet.rows[0].cells.teacher.status,'cancelled');});
test('B completes once; C network failure queues bounded retry and recovers automatically',async()=>{let upstream=0,downstream=0;const e=new Scheduler(example(),async p=>{if(p.prompt.includes('作为日语老师')){downstream++;if(downstream===1)throw new ModelError('连接中断','network',true);return ok('老师解读');}upstream++;return ok('フレームは枠です。');});e.run(e.targets('all'),{...opt,concurrency:1,autoRetry:true,apiMaxRetries:2,retryDelayMs:100});await new Promise(r=>setTimeout(r,30));assert.equal(e.running,0);assert.equal(e.queued,1);assert.equal(e.sheet.rows[0].cells.teacher.status,'queued');assert.match(e.sheet.rows[0].cells.teacher.error!,/自动重试/);await finish(e);assert.equal(upstream,1);assert.equal(downstream,2);assert.equal(e.sheet.rows[0].cells.teacher.status,'done');assert.equal(e.running,0);assert.equal(e.queued,0);assert.ok(e.steps.some(s=>s.phase.includes('自动重试 1/2')));});
test('retry limit and switch prevent infinite calls; permanent errors never auto retry',async()=>{for(const [enabled,error,expected] of [[true,new ModelError('限流','rate_limit',true),3],[false,new ModelError('断连','network',true),1],[true,new ModelError('无效密钥','invalid_key'),1],[true,new ModelError('余额不足','insufficient_quota'),1],[true,new ModelError('无权限','model_access'),1]] as const){let calls=0;const e=new Scheduler(example(),async()=>{calls++;throw error;});e.run(e.targets('all'),{...opt,autoRetry:enabled,apiMaxRetries:2,retryDelayMs:10});await finish(e);assert.equal(calls,expected);assert.equal(e.running,0);assert.equal(e.queued,0);assert.equal(e.sheet.rows[0].cells.explain.status,'error');assert.equal(e.sheet.rows[0].cells.teacher.status,'error');}});
test('stop or rapid edit while awaiting retry prevents the old retry request',async()=>{for(const action of ['stop','edit']){let calls=0;const e=new Scheduler(example(),async()=>{calls++;throw new ModelError('网络','network',true);});e.run(e.targets('all'),{...opt,autoRetry:true,retryDelayMs:100});await new Promise(r=>setTimeout(r,20));assert.equal(e.running,0);assert.equal(e.queued,2);if(action==='stop')e.stop();else{e.edit('row-1','input','新词');e.edit('row-1','input','最新词');}await new Promise(r=>setTimeout(r,200));assert.equal(calls,1);assert.equal(e.running,0);assert.equal(e.queued,0);}});
test('manual dependency delay is respected beyond the previous 0.5s constant',async()=>{let secondAt=0;const e=new Scheduler(example(),async p=>{if(p.prompt.includes('作为日语老师'))secondAt=Date.now();return ok('フレーム');});e.run(e.targets('all'),{...opt,dependencyDelayMs:900});await new Promise(r=>setTimeout(r,100));const completed=e.sheet.rows[0].cells.explain.completedAt!;assert.equal(e.running,0);assert.equal(e.queued,1);await finish(e);assert.ok(secondAt-completed>=895);});
test('timeout auto retry uses a fresh request and late response never replaces recovered output',async()=>{const late=deferred<ReturnType<typeof ok>>();let calls=0;const e=new Scheduler(example(),async()=>{calls++;return calls===1?late.promise:ok('已恢复');});e.run(e.targets('all'),{...opt,autoRetry:true,apiMaxRetries:1,retryDelayMs:10});await finish(e);assert.equal(calls,3);assert.equal(e.sheet.rows[0].cells.explain.value,'已恢复');late.resolve(ok('过期输出'));await new Promise(r=>setTimeout(r,10));assert.equal(e.sheet.rows[0].cells.explain.value,'已恢复');assert.equal(e.running,0);});
test('total deadline cancels a pending retry instead of leaving a spinner or retry timer',async()=>{let calls=0;const e=new Scheduler(example(),async()=>{calls++;throw new ModelError('断连','network',true);});e.run(e.targets('all'),{...opt,autoRetry:true,apiMaxRetries:2,retryDelayMs:40,totalTimeout:70});await finish(e);await new Promise(r=>setTimeout(r,100));assert.ok(calls<=2);assert.equal(e.running,0);assert.equal(e.queued,0);});
