'use client';
import { useState } from 'react';
import { X } from 'lucide-react';
import { personalRequest, type PersonalSettings } from '../model/personal';
import { providerNames, type Connection, type Provider } from '../model/credentials';
import { sessionFetch } from '../model/session';
export function ModelSettings({settings,onSaved,onClose}:{settings:PersonalSettings;onSaved:(settings:PersonalSettings)=>void;onClose:()=>void}){
  const [draft,setDraft]=useState<Connection>(settings.connection),[key,setKey]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[current,setCurrent]=useState(settings);
  async function save(remove=false,test=false){setBusy(true);setMessage('');try{
    const next=await personalRequest<PersonalSettings>('/api/settings',{revision:current.revision,connection:draft,...(remove?{modelKey:null}:key.trim()?{modelKey:key.trim()}:{})});setCurrent(next);onSaved(next);setKey('');
    if(test){const response=await sessionFetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await response.json() as {models?:string[];error?:{message:string}};if(!response.ok)throw Error(data.error?.message??'连接失败');setMessage(`已保存，连接测试通过，发现 ${data.models?.length??0} 个模型。`);}else setMessage(remove?'密钥已从服务器删除。':'已保存到服务器，其他设备登录后自动使用。');
  }catch(error){setMessage(error instanceof Error?error.message:'保存失败');}finally{setBusy(false);}}
  return <div className="overlay"><section role="dialog" aria-modal="true" aria-labelledby="server-model-title" className="dialog"><button className="close" aria-label="关闭模型设置" disabled={busy} onClick={onClose}><X size={20}/></button><h2 id="server-model-title">共享 AI 模型配置</h2><p>密钥在服务器加密保存，浏览器不能读取已保存的完整密钥。</p><label>提供商<select value={draft.provider} disabled={busy} onChange={e=>{setKey('');setDraft({...draft,provider:e.target.value as Provider});}}>{Object.entries(providerNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{draft.provider==='custom'&&<label>API 地址<input value={draft.customUrl} onChange={e=>setDraft({...draft,customUrl:e.target.value})}/></label>}{draft.provider==='local'&&<><label>本地服务<select value={draft.localProvider??'lmstudio'} onChange={e=>{const value=e.target.value as 'lmstudio'|'ollama';setDraft({...draft,localProvider:value,localUrl:value==='ollama'?'http://127.0.0.1:11434/v1':'http://127.0.0.1:1234/v1'});}}><option value="lmstudio">LM Studio</option><option value="ollama">Ollama</option></select></label><label>本机地址<input value={draft.localUrl??'http://127.0.0.1:1234/v1'} onChange={e=>setDraft({...draft,localUrl:e.target.value})}/></label></>}<label>API key<input type="password" autoComplete="off" maxLength={300} value={key} onChange={e=>setKey(e.target.value)} placeholder={current.modelKeyConfigured?'已配置 · 留空保留原密钥':'未配置'}/></label><p>修改服务地址会清除旧密钥。填写新密钥后点击保存；密钥不会进入工作簿导出。</p>{message&&<p role="status">{message}</p>}<div className="dialog-actions"><button className="button" disabled={busy} onClick={()=>void save(true)}>删除密钥</button><button className="button" disabled={busy} onClick={()=>void save(false,true)}>保存并测试</button><button className="button primary" disabled={busy} onClick={()=>void save()}>保存配置</button></div></section></div>;
}
